on:
  pull_request:
    branches:
     - main
jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate
        uses: dflook/terraform-validate@v1.29.1
